Learn Numpy with me. Part 1.
Simple and concise notebook to learn and revise on numpy!

In [1]:
import numpy as np
#After this we can access all functions and classes in the numpy module.

In [2]:
#creating an array called data
data = np.array([[1,2],[3,4],[5,6]])

In [3]:
print(type(data)) #tells us the datatype of array, data

<class 'numpy.ndarray'>


In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim #returns the number of dimensions(axes) of the array

2

In [6]:
data.shape #returns the a tuple of the number of elements in each dimension

(3, 2)

In [7]:
data.size #returns the number of elements in the array

6

In [8]:
data.dtype

dtype('int64')

In [9]:
data.nbytes

48

Creating arrays from other array-like objects
and lists

In [10]:
z = np.zeros((2,3),int) 
z
#returns an array of all elements as zeros.
#((rows,columns), datatype)

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
np.ones((2,3), float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
z.fill(5)
z
#Used to fill an already created array with an element

array([[5, 5, 5],
       [5, 5, 5]])

In [13]:
e = np.empty(5)
e

array([4.66335836e-310, 0.00000000e+000, 4.66437724e-310, 4.66437724e-310,
       2.37151510e-322])

In [14]:
e.fill(4)
e

array([4., 4., 4., 4., 4.])

Increamental Sequences


In [15]:
np.arange(0, 10, 1)
#(Start, end, increament)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0,10,20)
#(start,end, number of elements)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [17]:
np.logspace(0,10, 5)
#(start, end, powers of the optional base keyword argument which defaults to base 10)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

Arrays with properties of other arrays

In [18]:
def f(x):
    y = np.ones_like(x)
    return y
#created a function which returns an array with same size, data type as x

In [19]:
x = np.arange(0,5,1)
x

array([0, 1, 2, 3, 4])

In [20]:
#calling function f
f(x)

array([1, 1, 1, 1, 1])

Matrix Arrays

In [21]:
M = np.identity(4)
M
#returns an identity matrix with 4 rows


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(3, k=1)
#returns a matrix with ones on the diagonal with an optional offset


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [23]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [24]:
np.diag(np.arange(0,20,5), k =0)

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

Indexing and slicing

For One Dimensional Arrays




a[m]          select element at index m, where m is and integer.

a[m:n]        select elements with index starting at m and wnding at n-1.

a[m:n:p]      select elements with index starting from m through n inclusive with increment p.

For Multidimensional Arrays.......  

RESHAPING AND RESIZING

In [25]:
M

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
data = np.array([[1,2],[3,4]])

In [27]:
data

array([[1, 2],
       [3, 4]])

In [31]:
np.reshape(data, (1,4)) 
#reshapes the array into a 1x4 array
#Note that not all arrays can be reshaped into certain shapes
#It depends on the number of elements in the array

array([[1, 2, 3, 4]])

In [32]:
data

array([[1, 2],
       [3, 4]])

In [34]:
data.ravel()
#Collapses all dimensions of the array a one dimensional array

array([1, 2, 3, 4])

In [35]:
data


array([[1, 2],
       [3, 4]])

In [38]:
data2 = np.vstack((data,data))
data2
#stacks up data onto data vertically

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [41]:
data3 = np.hstack((data2,data2))
data3
#stacks up data onto data horizontally

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

FOLLOW TO CHAPTER 2 FOR MORE ON NUMPY!!!
